#!/bin/bash

LINEWIDTH=2

gnuplot -persist << EOF
set title "$1"
set ylabel "altitude (m)"
set y2label "velocity (m/s), acceleration(m/s²)"
set xlabel "time (s)"
set xtics border out nomirror
set ytics border out nomirror
set y2tics border out nomirror
set style line 1 linewidth $LINEWIDTH
set style line 2 linewidth $LINEWIDTH
set style line 3 linewidth $LINEWIDTH
set style line 4 linewidth $LINEWIDTH
set style line 5 linewidth $LINEWIDTH
set style line 6 linewidth $LINEWIDTH
set style line 7 linewidth $LINEWIDTH dashtype 2
set style line 8 linewidth $LINEWIDTH dashtype 2
set style line 9 linewidth $LINEWIDTH dashtype 2
set style line 10 linewidth $LINEWIDTH dashtype 2
plot "$1" using 1:3 with lines axes x1y1 title "raw height" ls 1,\
"$1" using 1:5 with lines axes x1y2 title "raw accel" ls 2,\
"$1" using 1:7 with lines axes x1y2 title "accel speed" ls 3,\
"$1" using 1:11 with lines axes x1y1 title "height" ls 4,\
"$1" using 1:13 with lines axes x1y2 title "speed" ls 5,\
"$1" using 1:15 with lines axes x1y2 title "accel" ls 6,\
"$1" using 1:19 with lines axes x1y1 title "drogue" ls 7,\
"$1" using 1:21 with lines axes x1y1 title "main" ls 8,\
"$1" using 1:23 with lines axes x1y1 title "error" ls 9,\
"$1" using 1:9 with lines axes x1y2 title "state" ls 10
EOF
