#!/bin/sh

VERSION=3.0
PRODUCT=TeleMini
BASE=`echo $PRODUCT | tr 'A-Z' 'a-z'`

echo "$PRODUCT-v$VERSION Test Program"
echo "Copyright 2017 by Keith Packard.  Released under GPL v2 or later"
echo
echo "Expectations:"
echo "\t$PRODUCT v$VERSION powered from USB"
echo

ret=1
ao-list | while read product serial dev; do
    case "$product" in
	"$PRODUCT-v$VERSION")

	    echo "Testing $product $serial $dev"
	    echo ""

	    ./test-igniters "$dev" --rplus=100 --rminus=27 --adcmax=4095 drogue main
	    echo ""

	    echo "Testing baro sensor"
	    ../ao-tools/ao-test-baro/ao-test-baro --tty="$dev"

	    case $? in
		0)
		    ;;
		*)
		    echo "failed"
		    exit 1
	    esac
	    echo""

	    FLASHSIZE=524288

	    echo "Testing flash"
	    ../ao-tools/ao-test-flash/ao-test-flash --tty="$dev" "$FLASHSIZE"

	    case $? in
		0)
		    ;;
		*)
		    echo "failed"
		    exit 1
	    esac
	    echo""

	    echo "$PRODUCT-v$VERSION" serial "$serial" is ready to ship
	    echo "\007"
	    ret=0
	    ;;
    esac
done
