#!/bin/sh

VERSION=1
PRODUCT=EasyTimer
BASE=`echo $PRODUCT | tr 'A-Z' 'a-z'`

echo "$PRODUCT-v$VERSION Test Program"
echo "Copyright 2020 by Bdale Garbee.  Released under GPL v3"
echo
echo "Expectations:"
echo "\t$PRODUCT v$VERSION powered from USB"
echo

ret=1
ao-list | while read product serial dev; do
    case "$product" in
	"$PRODUCT-v$VERSION")

	    echo "Testing $product $serial $dev"

	    ./test-igniters $dev 0 1
	    echo""

	    case $? in
		0)
		    ;;
		*)
		    echo "failed"
		    exit 1
	    esac
	    echo""

	    echo "$PRODUCT-v$VERSION" serial "$serial" is ready to ship
	    echo "\007"
	    ret=0
	    ;;
    esac
done
