#!/bin/sh

if [ -x /usr/bin/ao-flash-stm ]; then
	FLASH_STM=/usr/bin/ao-flash-stm
else
	echo "Can't find ao-flash-stm!  Aborting."
	exit 1
fi

if [ -x /usr/bin/ao-usbload ]; then
	USBLOAD=/usr/bin/ao-usbload
else
	echo "Can't find ao-usbload!  Aborting."
	exit 1
fi

VERSION=1
REPO=~/altusmetrumllc/Binaries
PRODUCT=EasyTimer

echo "$PRODUCT v$VERSION Turn-On and Calibration Program"
echo "Copyright 2020 by Bdale Garbee.  Released under GPL v3"
echo
echo "Expectations:"
echo "\t$PRODUCT v$VERSION powered from USB"
echo "\t\twith ST-Link-V2 cabled to debug header"
echo

case $# in
    1)
	SERIAL="$1"
	echo "$PRODUCT-$VERSION serial number: $SERIAL" 
	;;
    0)
	echo -n "$PRODUCT-$VERSION serial number: "
	read SERIAL
	;;
    *)
	echo "Usage: $0 <serial-number>" 1>&2
	exit 1;
	;;
esac

echo $FLASH_STM

$FLASH_STM $REPO/loaders/easytimer-v$VERSION*.elf 

sleep 3

$USBLOAD --serial=$SERIAL --force $REPO/easytimer-v$VERSION*.elf || exit 1

sleep 5

dev=`ao-list | awk '/EasyTimer-v'"$VERSION"'/ { print $3; exit(0); }'`

case "$dev" in
/dev/tty*)
	echo "EasyTimer found on $dev"
	;;
*)
	echo 'No EasyTimer-v'"$VERSION"' found'
	exit 1
	;;
esac

echo 'E 0' > $dev

failed=1
while [ $failed = 1 ]; do
    ../ao-tools/ao-cal-accel/ao-cal-accel $dev
    failed=$?
done

echo 'E 1' > $dev

./test-easytimer

exit $?
