== Configuration

	There is very little that must be configured to make EasyMotor work.
	In fact, the default configuration from the factory is typically
	sufficient without change.

	=== Connecting to a Unit

		To change any EasyMotor configuration, you need to attach
		a battery and a power switch, then use a micro USB cable
		to connect the board to a computer running AltosUI.

	=== Changing the Configuration

		All available configuration options can be set using the 
		“Configure Altimeter” menu selection within the AltosUI
		program.

