= Release Notes for Version 1.9.7
include::release-head.adoc[]
:doctype: article

	Version 1.9.7

	== AltOS

	* Fix TeleGPS logging so that new data are appended to an existing log correctly

	== AltosUI

	* Support Mac OS X 11 (Big Sur)

	* Support Monitor Idle on Easy Timer

	* Fix TeleMega v4.0 and TeleMetrum v3.0 configuration in Antenna Down mode

	* Show launch sites in Load Maps view

	* Add IMU header names to CSV files

	* Clean up TeleGPS log corruption due to firmware bugs during firmware update

	== AltosDroid

	* Support older devices back to Android version 5.1

	* Fix a number of issues that could result in app crashes
