= Release Notes for Version 1.9.8
include::release-head.adoc[]
:doctype: article

	Version 1.9.8

	== AltOS

	* Add support for TeleMega v5.0

	* Extend extra pyro channel times to support delay > 327 seconds

	== AltosUI

	* Support ARM devices in Linux binary release

	* Add support for TeleMega v5.0

	== AltosDroid

	* Show tilt angle in pad and flight tabs

	* Show altitude as well as height (useful for TeleGPS)

	* Support devices without GPS receivers

	== MicroPeak GUI

	* Show error dialog if device open fails